# Generated by Django 5.2.3 on 2025-12-22 05:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('best_score', models.IntegerField(default=0, verbose_name='最高スコア')),
                ('total_score', models.IntegerField(default=0, verbose_name='累計スコア')),
                ('initial_points', models.IntegerField(default=0, verbose_name='初期ポイント')),
                ('total_plays', models.IntegerField(default=0, verbose_name='総プレイ回数')),
                ('total_clears', models.IntegerField(default=0, verbose_name='クリア回数')),
                ('highest_stage', models.IntegerField(default=1, verbose_name='最高到達ステージ')),
                ('unlocked_jobs', models.JSONField(default=list, verbose_name='開放済みジョブ')),
                ('bonus_hp', models.IntegerField(default=0, verbose_name='HP引き継ぎボーナス')),
                ('bonus_atk', models.IntegerField(default=0, verbose_name='攻撃力引き継ぎボーナス')),
                ('bonus_def', models.IntegerField(default=0, verbose_name='防御力引き継ぎボーナス')),
                ('bonus_spd', models.IntegerField(default=0, verbose_name='素早さ引き継ぎボーナス')),
                ('first_clear_date', models.DateTimeField(blank=True, null=True, verbose_name='初回クリア日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
