# スコアポイント設定（複数の関数で使用されるため、ここに定義）
JOB_CONFIG_KEY_MAP = {
    "戦士": "warrior",
    "魔法使い": "magic",
    "忍者": "ninja",
    "格闘家": "martial",
    "侍": "samurai",
}

SCORE_POINT_CONFIG = {
    "all": [
        {"key": "hp", "label": "HP", "base": 100, "inc": 5},
        {"key": "atk", "label": "ATK", "base": 5, "inc": 1},
        {"key": "def", "label": "DEF", "base": 5, "inc": 1},
        {"key": "spd", "label": "SPD", "base": 5, "inc": 1},
        {"key": "mp", "label": "SP", "base": 50, "inc": 5},
        {"key": "gold", "label": "初期G", "base": 100, "inc": 50},
        {"key": "gold_rate", "label": "G獲得倍率", "base": 1.0, "inc": 0.05, "format": "{:.2f}"},
        {"key": "exp_rate", "label": "EXP獲得倍率", "base": 1.0, "inc": 0.05, "format": "{:.2f}"},
    ],
    "warrior": [
        {"key": "job_bonus_hp", "label": "ジョブボーナス<br>HP", "base": 10, "inc": 1},
        {"key": "job_bonus_atk", "label": "ジョブボーナス<br>ATK", "base": 3, "inc": 1},
        {"key": "job_bonus_def", "label": "ジョブボーナス<br>DEF", "base": 3, "inc": 1},
        {"key": "job_bonus_spd", "label": "ジョブボーナス<br>SPD", "base": -3, "inc": 1},
        {"key": "job_bonus_mp", "label": "ジョブボーナス<br>SP", "base": -5, "inc": 1},
        {
            "key": "skill_warrior_konshin_slash",
            "label": "渾身斬り<br>倍率",
            "base": 2.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "渾身斬り",
            "effect_type": "attack",
        },
        {
            "key": "skill_warrior_body_boost_atk",
            "label": "身体強化<br>ATK倍率",
            "base": 1.5,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "身体強化",
            "effect_type": "buf",
            "stat": "atk",
        },
        {
            "key": "skill_warrior_body_boost_def",
            "label": "身体強化<br>DEF倍率",
            "base": 1.5,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "身体強化",
            "effect_type": "buf",
            "stat": "def",
        },
        {
            "key": "skill_warrior_intimidate_atk",
            "label": "気迫<br>ATK倍率",
            "base": 0.7,
            "inc": -0.1,
            "format": "{:.1f}",
            "min": 0.1,
            "skill_name": "気迫",
            "effect_type": "debuf",
            "stat": "atk",
        },
        {
            "key": "skill_warrior_intimidate_def",
            "label": "気迫<br>DEF倍率",
            "base": 0.7,
            "inc": -0.1,
            "format": "{:.1f}",
            "min": 0.1,
            "skill_name": "気迫",
            "effect_type": "debuf",
            "stat": "def",
        },
    ],
    "magic": [
        {"key": "job_bonus_hp", "label": "ジョブボーナス<br>HP", "base": -5, "inc": 1},
        {"key": "job_bonus_atk", "label": "ジョブボーナス<br>ATK", "base": 10, "inc": 1},
        {"key": "job_bonus_def", "label": "ジョブボーナス<br>DEF", "base": -2, "inc": 1},
        {"key": "job_bonus_spd", "label": "ジョブボーナス<br>SPD", "base": 0, "inc": 1},
        {"key": "job_bonus_mp", "label": "ジョブボーナス<br>SP", "base": 10, "inc": 1},
        {
            "key": "skill_magic_impact_meteor",
            "label": "インパクトメテオ<br>倍率",
            "base": 3.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "インパクトメテオ",
            "effect_type": "attack",
        },
        {
            "key": "skill_magic_power_boost_atk",
            "label": "魔力強化<br>ATK倍率",
            "base": 2.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "魔力強化",
            "effect_type": "buf",
            "stat": "atk",
        },
        {
            "key": "skill_magic_shield_def",
            "label": "マジックシールド<br>DEF倍率",
            "base": 3.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "マジックシールド",
            "effect_type": "buf",
            "stat": "def",
        },
    ],
    "ninja": [
        {"key": "job_bonus_hp", "label": "ジョブボーナス<br>HP", "base": -5, "inc": 1},
        {"key": "job_bonus_atk", "label": "ジョブボーナス<br>ATK", "base": 3, "inc": 1},
        {"key": "job_bonus_def", "label": "ジョブボーナス<br>DEF", "base": 0, "inc": 1},
        {"key": "job_bonus_spd", "label": "ジョブボーナス<br>SPD", "base": 5, "inc": 1},
        {"key": "job_bonus_mp", "label": "ジョブボーナス<br>SP", "base": 0, "inc": 1},
        {
            "key": "skill_ninja_vital_strike",
            "label": "急所突き<br>倍率",
            "base": 2.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "急所突き",
            "effect_type": "attack",
        },
        {
            "key": "skill_ninja_shadow_clone_spd",
            "label": "影分身<br>SPD倍率",
            "base": 1.8,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "影分身",
            "effect_type": "buf",
            "stat": "spd",
        },
    ],
    "martial": [
        {"key": "job_bonus_hp", "label": "ジョブボーナス<br>HP", "base": -20, "inc": 1},
        {"key": "job_bonus_atk", "label": "ジョブボーナス<br>ATK", "base": 8, "inc": 1},
        {"key": "job_bonus_def", "label": "ジョブボーナス<br>DEF", "base": 3, "inc": 1},
        {"key": "job_bonus_spd", "label": "ジョブボーナス<br>SPD", "base": 5, "inc": 1},
        {"key": "job_bonus_mp", "label": "ジョブボーナス<br>SP", "base": -10, "inc": 1},
        {
            "key": "skill_martial_spirit_punch",
            "label": "気合いパンチ<br>倍率",
            "base": 2.2,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "気合いパンチ",
            "effect_type": "attack",
        },
        {
            "key": "skill_martial_shadowing_atk",
            "label": "シャドーイング<br>ATK倍率",
            "base": 1.5,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "シャドーイング",
            "effect_type": "buf",
            "stat": "atk",
        },
        {
            "key": "skill_martial_shadowing_spd",
            "label": "シャドーイング<br>SPD倍率",
            "base": 1.5,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "シャドーイング",
            "effect_type": "buf",
            "stat": "spd",
        },
        {
            "key": "skill_martial_combo_punch",
            "label": "連続パンチ<br>倍率",
            "base": 0.09,
            "inc": 0.01,
            "format": "{:.2f}",
            "max": 10.0,
            "skill_name": "連続パンチ",
            "effect_type": "action",
        },
    ],
    "samurai": [
        {"key": "job_bonus_hp", "label": "ジョブボーナス<br>HP", "base": -10, "inc": 1},
        {"key": "job_bonus_atk", "label": "ジョブボーナス<br>ATK", "base": 10, "inc": 1},
        {"key": "job_bonus_def", "label": "ジョブボーナス<br>DEF", "base": 0, "inc": 1},
        {"key": "job_bonus_spd", "label": "ジョブボーナス<br>SPD", "base": 5, "inc": 1},
        {"key": "job_bonus_mp", "label": "ジョブボーナス<br>SP", "base": -20, "inc": 1},
        {
            "key": "skill_samurai_iai_slash",
            "label": "居合斬り<br>倍率",
            "base": 2.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "居合斬り",
            "effect_type": "attack",
        },
        {
            "key": "skill_samurai_meditation_atk",
            "label": "瞑想<br>ATK倍率",
            "base": 1.8,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "瞑想",
            "effect_type": "buf",
            "stat": "atk",
        },
        {
            "key": "skill_samurai_sen_timing",
            "label": "刹那の見切り<br>倍率",
            "base": 1.0,
            "inc": 0.1,
            "format": "{:.1f}",
            "max": 10.0,
            "skill_name": "刹那の見切り",
            "effect_type": "action",
        },
    ],
}


def build_score_bonus_defaults():
    all_defaults = {}
    for cfg in SCORE_POINT_CONFIG.get("all", []):
        all_defaults[cfg["key"]] = cfg["base"]

    job_defaults = {}
    for job_name, config_key in JOB_CONFIG_KEY_MAP.items():
        config_list = SCORE_POINT_CONFIG.get(config_key, [])
        job_defaults[job_name] = {cfg["key"]: cfg["base"] for cfg in config_list}

    return all_defaults, job_defaults
