# Generated by Django 5.2.3 on 2025-08-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_enemy_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defeats',
            field=models.IntegerField(default=0),
        ),
    ]
