# Generated by Django 5.2.3 on 2025-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_enemy_is_defeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
