# Generated by Django 5.2.3 on 2025-09-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_enemy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='atk_default',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='enemy',
            name='defense_default',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enemy',
            name='exp_default',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_hp_default',
            field=models.IntegerField(default=50),
        ),
    ]
