# Generated by Django 5.2.3 on 2025-09-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_enemy_atk_default_enemy_defense_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='level_default',
            field=models.IntegerField(default=1),
        ),
    ]
