# Generated by Django 5.2.3 on 2025-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_enemy_level_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='spd',
            field=models.IntegerField(default=5),
        ),
    ]
