# Generated by Django 5.2.3 on 2025-09-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_enemy_spd_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spd',
            field=models.IntegerField(default=5),
        ),
    ]
