# Generated by Django 5.2.3 on 2025-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_player_spd'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_mp',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='mp',
            field=models.IntegerField(default=50),
        ),
    ]
