# Generated by Django 5.2.3 on 2025-10-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_player_max_mp_player_mp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equipment_type', models.CharField(choices=[('weapon', '武器'), ('armor', '防具')], max_length=10)),
                ('atk_bonus', models.IntegerField(default=0)),
                ('def_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('spd_bonus', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('drop_rate', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='enemy',
            name='drop_equipment',
            field=models.ManyToManyField(blank=True, related_name='dropped_by', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_armor', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='player',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_weapon', to='game.equipment'),
        ),
    ]
