# Generated by Django 5.2.3 on 2025-11-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='drop_gold',
            field=models.IntegerField(default=20),
        ),
    ]
