# Generated by Django 5.2.3 on 2025-12-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_enemy_drop_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
