# Generated by Django 5.2.3 on 2025-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_owned_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='is_strong',
            field=models.BooleanField(default=False),
        ),
    ]
