# Generated by Django 5.2.3 on 2025-12-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_enemy_is_strong'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_stock',
            field=models.IntegerField(default=10),
        ),
    ]
