# Generated by Django 5.2.3 on 2025-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_player_total_atk_battle_player_total_def_battle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinventory',
            options={'verbose_name': 'プレイヤーアイテム', 'verbose_name_plural': 'プレイヤーアイテム'},
        ),
        migrations.AddField(
            model_name='enemy',
            name='drop_gold_default',
            field=models.IntegerField(default=20),
        ),
    ]
