# Generated by Django 5.2.3 on 2025-12-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_player_profile_player_is_guest_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='appearance_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
