# Generated by Django 5.2.3 on 2026-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_enemy_appearance_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='atk_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='defense_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='drop_gold_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='exp_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='level_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='max_hp_default',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='spd_default',
        ),
        migrations.AddField(
            model_name='enemy',
            name='appear_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='base_atk',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='enemy',
            name='base_def',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enemy',
            name='base_exp',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='enemy',
            name='base_max_hp',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='enemy',
            name='base_spd',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='enemy',
            name='drop_gold_base',
            field=models.IntegerField(default=20),
        ),
    ]
