# Generated by Django 5.2.3 on 2026-01-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_remove_enemy_atk_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='appear_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='appear_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='next_exp',
            field=models.IntegerField(default=300),
        ),
    ]
