# Generated by Django 5.2.3 on 2026-01-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_equipment_appear_level_item_appear_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='image_url',
            field=models.CharField(default='game/img/スライム.png', max_length=200),
        ),
    ]
