# Generated by Django 5.2.3 on 2026-01-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_delete_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='strong_defeats',
            field=models.IntegerField(default=0),
        ),
    ]
