# Generated by Django 5.2.3 on 2026-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_equipment_score_player_strong_defeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='death_count',
            field=models.IntegerField(default=0),
        ),
    ]
