# Generated by Django 5.2.3 on 2026-01-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_player_death_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='target',
            field=models.CharField(choices=[('sp', 'SP'), ('hp', 'HP')], max_length=10),
        ),
    ]
