# Generated by Django 5.2.3 on 2026-01-21 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_questtemplate_condition_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_type', models.CharField(choices=[('home', 'ホーム画面'), ('battle', '戦闘画面'), ('shop', 'ショップ'), ('status', 'ステータス'), ('quest', 'クエスト')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザーチュートリアル',
                'verbose_name_plural': 'ユーザーチュートリアル',
                'unique_together': {('user', 'tutorial_type')},
            },
        ),
    ]
