# Generated by Django 5.2.3 on 2026-01-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_enemy_attack_effect_enemy_attack_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='attack_effect',
            field=models.FileField(blank=True, null=True, upload_to='game/effects/attacks/'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='attack_sound',
            field=models.FileField(blank=True, null=True, upload_to='game/sounds/attacks/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attack_effect',
            field=models.FileField(blank=True, null=True, upload_to='game/effects/attacks/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attack_sound',
            field=models.FileField(blank=True, null=True, upload_to='game/sounds/attacks/'),
        ),
    ]
