# Generated by Django 5.2.3 on 2026-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_merge_20260127_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='gold_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS game_usertutorial',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='UserTutorial',
                ),
            ],
        ),
    ]
