# Generated by Django 5.2.3 on 2025-07-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('unlocked_jobs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('hp', models.IntegerField(default=100)),
                ('atk', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('stat_points', models.IntegerField(default=0)),
                ('job', models.CharField(default='戦士', max_length=20)),
                ('item', models.CharField(default='なし', max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
