# Generated by Django 5.2.3 on 2025-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_hp', models.IntegerField(default=50)),
                ('hp', models.IntegerField(default=50)),
                ('atk', models.IntegerField(default=8)),
                ('defense', models.IntegerField(default=3)),
            ],
        ),
    ]
