# Generated by Django 5.2.3 on 2025-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_exp',
            field=models.IntegerField(default=500),
        ),
    ]
