# Generated by Django 5.2.3 on 2025-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_next_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='exp',
            field=models.IntegerField(default=120),
        ),
    ]
