# Generated by Django 5.2.3 on 2025-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_defeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='is_defeated',
            field=models.BooleanField(default=False),
        ),
    ]
