# Generated by Django 5.2.3 on 2025-09-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_enemy_spd'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='spd_default',
            field=models.IntegerField(default=5),
        ),
    ]
