# Generated by Django 5.2.3 on 2025-11-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_equipment_player_gold_enemy_drop_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target', models.CharField(choices=[('mp', 'MP'), ('hp', 'HP')], max_length=10)),
                ('effect_amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
