# Generated by Django 5.2.3 on 2025-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_equipment_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
