# Generated by Django 5.2.3 on 2025-12-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_item_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='owned_equipment',
            field=models.ManyToManyField(blank=True, related_name='owned_by_players', to='game.equipment'),
        ),
    ]
