# Generated by Django 5.2.3 on 2025-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_playerinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unlock_level', models.IntegerField(default=0)),
                ('background_image', models.CharField(max_length=100)),
                ('min_enemy_level', models.IntegerField(default=1)),
                ('max_enemy_level', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='enemy',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='enemies', to='game.stage'),
        ),
    ]
