# Generated by Django 5.2.3 on 2025-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_stage_enemy_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_atk_battle',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='total_def_battle',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='total_hp_battle',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='total_max_hp_battle',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='total_spd_battle',
            field=models.IntegerField(default=5),
        ),
    ]
