# Generated by Django 5.2.3 on 2026-01-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_enemy_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('life', 'ライフ'), ('account', 'アカウント')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('defeat_enemy', '敵を倒す'), ('spend_gold', 'ゴールドを使う')], max_length=20)),
                ('condition_target', models.CharField(blank=True, max_length=50)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_max', models.IntegerField(default=1)),
                ('reward_exp', models.IntegerField(default=0)),
                ('reward_gold', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.player')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
