# Generated by Django 5.2.3 on 2026-01-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('life', 'ライフ'), ('account', 'アカウント')], max_length=10)),
                ('job', models.CharField(choices=[('all', '全職業'), ('戦士', '戦士'), ('魔法使い', '魔法使い'), ('盗賊', '盗賊')], default='all', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('defeat_enemy', '敵を倒す'), ('spend_gold', 'ゴールドを使う')], max_length=20)),
                ('condition_target', models.CharField(blank=True, max_length=50)),
                ('progress_max', models.IntegerField(default=1)),
                ('reward_exp', models.IntegerField(default=0)),
                ('reward_gold', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'クエストテンプレート',
                'verbose_name_plural': 'クエストテンプレート',
                'ordering': ['quest_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_current', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='game.player')),
                ('quest_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progresses', to='game.questtemplate')),
            ],
            options={
                'verbose_name': 'プレイヤークエスト',
                'verbose_name_plural': 'プレイヤークエスト',
                'unique_together': {('player', 'quest_template')},
            },
        ),
    ]
