# Generated by Django 5.2.3 on 2026-01-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_questtemplate_playerquest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
