# Generated by Django 5.2.3 on 2026-01-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_alter_item_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='questtemplate',
            name='derivation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questtemplate',
            name='derived_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_quest', to='game.questtemplate'),
        ),
        migrations.AlterField(
            model_name='item',
            name='target',
            field=models.CharField(choices=[('mp', 'SP'), ('hp', 'HP')], max_length=10),
        ),
    ]
