# Generated by Django 5.2.3 on 2026-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_questtemplate_derivation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questtemplate',
            name='condition_type',
            field=models.CharField(choices=[('defeat_enemy', '敵を倒す'), ('defeat_strong_enemy', '強敵を倒す'), ('spend_gold', 'ゴールドを使う')], max_length=20),
        ),
    ]
