# Generated by Django 5.2.3 on 2026-01-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_usertutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='attack_effect',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enemy',
            name='attack_sound',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='attack_effect',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='attack_sound',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
